---
title: "Prediction Assignment Writeup"
author: "Xiang Li"
date: "6/10/2017"
output: html_document
---
### libray
```{r}
library(dplyr)
library(caret)
library(rpart.plot)
```

###read the data
```{r}
train<-read.csv("./pml-training.csv")
test<-read.csv("./pml-testing.csv")
train<-tbl_df(train)
test<-tbl_df(test)
```
### remove data with NAs and blanks
```{r}
train[train==""]<-NA
table(is.na(train))
countna<-function(x){length(which(is.na(x)))}
nalist<-apply(train,2,countna)
nalist<-tbl_df(nalist)
nacol<-which(nalist>50)
train<-train[,-nacol]
test<-test[,-nacol]
table(is.na(train))
```
### remove unnessary data
```{r}
train<-train[,-c(1:7)]
test<-test[,-c(1:7)]
```
### Build up a model
```{r}
modFitDecTree <- rpart(classe ~., data = train, method="class")
rpart.plot(modFitDecTree)
```
### Confusion Matrix
```{r}
predict <- predict(modFitDecTree, newdata=train, type="class")
actual<-train$classe
confusionMatrix(actual,predict)
```
### Predict
```{r}
predictDecTree <- predict(modFitDecTree, newdata=test, type="class")
predictDecTree
```

